#!/usr/bin/env python3
"""
Tkinter for Python 2 
tkinter for Python 3 
"""
import tkinter as tk
from tkinter import filedialog
from tkinter import messagebox
import pandas as pd

#Canvas and Title (Label)

root = tk.Tk()

root.title("CSV to JSON")

first_canvas = tk.Canvas(root, width = 300, height = 300, bg
        = "linen", relief = "raised")
first_canvas.pack() 

first_label = tk.Label(root, text = "File Conversion (CSV to JSON)", bg
        = "linen")
first_label.config(font=("helvetica", 15)) 
first_canvas.create_window(150, 60, window = first_label) 

#Functions 
def getCSV(): 
    global read_file
    import_file = filedialog.askopenfilename()
    read_file = pd.read_csv(import_file)

# getCSV button 
browse_button = tk.Button(text = "      Import CSV File     ", command
        = getCSV, bg = "skyblue", fg = "white", font = ("helvetica", 12, "bold"))
first_canvas.create_window(150, 130, window = browse_button)

# convert to json function
def convertJSON(): 
    global read_file
    export_file = filedialog.asksaveasfilename(defaultextension = ".json")
    read_file.to_json(export_file)

save_as = tk.Button(text = "        Convert to JSON     ",command
        = convertJSON, bg= "skyblue", fg = "white", font = ("helvetica", 12,
            "bold"))
first_canvas.create_window(150, 180, window = save_as)

#exit
def q(): 
    message_box = tk.messagebox.askquestion("Exit Application", "Do you want to exit?", icon = "warning")
    if message_box == "yes": 
        root.destroy()

exit_button = tk.Button(root, text = "      Exit Application        ",
        command=q, bg = "brown", fg = "white", font=("helvetica", 12, "bold"))
first_canvas.create_window(150, 230, window = exit_button)

root.mainloop()
